#!/bin/bash -e
echo
echo "### removing mongo ##"

# delete mongo if exists
if ! [[ -z `docker inspect --format="{{ .State.Running }}" mongodb` ]]; then
  docker rm -f mongodb
fi

echo
echo "### running mongodb ###"
echo

MAX_NETWORK=${MAX_NETWORK:='max-network'}
MAX_MONGO_HOST=${MAX_MONGO_HOST:='172.18.0.26'}
echo "MAX_NETWORK: $MAX_NETWORK"
echo "MAX_MONGO_HOST: $MAX_MONGO_HOST"
echo

docker run -d --name mongodb -h mongodb \
--network $MAX_NETWORK \
--ip $MAX_MONGO_HOST \
-p 27017:27017 \
-e MONGO_INITDB_ROOT_USERNAME=root \
-e MONGO_INITDB_ROOT_PASSWORD=secret \
-e APP_USER=appUser \
-e APP_PWD=appUser \
-e DB_NAME=bootcampDb \
-e DB_COLLECTION_NAME=bootcamp \
-v ~/docker-volumes/mongo-data:/data/db \
mongo