#!/bin/bash -e
echo
echo "### removing mysql"

# delete mysql if exists
if ! [[ -z `docker inspect --format="{{ .State.Running }}" mysql` ]]; then
  docker rm -f mysql
fi

echo
echo "### running mysql ###"
echo

MAX_NETWORK=${MAX_NETWORK:='max-network'}
MAX_MYSQL_HOST=${MAX_MYSQL_HOST:='172.18.0.10'}
echo "MAX_NETWORK: $MAX_NETWORK"
echo "MAX_MYSQL_HOST: $MAX_MYSQL_HOST"
echo

docker run -d --name mysql -h mysql \
--network $MAX_NETWORK \
--ip $MAX_MYSQL_HOST \
-p 3306:3306 \
-e MYSQL_DATABASE=bootcampDb \
-e MYSQL_ROOT_PASSWORD=secret \
-e MYSQL_USER=user \
-e MYSQL_PASSWORD=secret \
-v ~/docker-volumes/mysql-data:/var/lib/mysql \
-v ~/docker-volumes/mysql-tmp:/tmp/mysql \
mysql:8.0.20 \
--character-set-server=utf8mb4 \
--collation-server=utf8mb4_unicode_ci \
--max_allowed_packet=1024M \
--max_connections=1500 \
--interactive_timeout=900 \
--wait_timeout=900 \
--lower_case_table_names=1 \
--net_write_timeout=3600 \
--net_read_timeout=3600 \
--connect_timeout=900